services:
  - type: web
    name: complaint-management-system
    plan: free
    runtime: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8044
